POST http://localhost:3000/api/auth/register HTTP/1.1
content-type: application/json

{
    "displayName": "Bob Bobby",
    "password": "123456",
    "username": "bobby123",
    "emailAddress": "Bobby@email.com"
}

###
POST http://localhost:3000/api/auth/login HTTP/1.1
content-type: application/json

{
    "password": "123456",
    "username": "bobby123"
}

###
GET http://localhost:3000/api/auth/logout HTTP/1.1
content-type: application/json

###
GET http://localhost:3000/api/movies/list HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNGUwZTNlNjBiY2I2ZTJkZTA0ZjMwMCIsImRpc3BsYXlOYW1lIjoiQm9iIEJvYmJ5IiwidXNlcm5hbWUiOiJib2JieTEyMyIsImlhdCI6MTY2NjEzNTY1NCwiZXhwIjoxNjY2NzQwNDU0fQ.azX1i7gLJzFOQzUHRCIiFFMg-UogDLaMzG3DOaz8CKM

###
GET http://localhost:3000/api/movies/633cc5bc223907de800aaff6 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNGUwZTNlNjBiY2I2ZTJkZTA0ZjMwMCIsImRpc3BsYXlOYW1lIjoiQm9iIEJvYmJ5IiwidXNlcm5hbWUiOiJib2JieTEyMyIsImlhdCI6MTY2NjEzNTY1NCwiZXhwIjoxNjY2NzQwNDU0fQ.azX1i7gLJzFOQzUHRCIiFFMg-UogDLaMzG3DOaz8CKM


###
POST http://localhost:3000/api/movies/add HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNGUwZTNlNjBiY2I2ZTJkZTA0ZjMwMCIsImRpc3BsYXlOYW1lIjoiQm9iIEJvYmJ5IiwidXNlcm5hbWUiOiJib2JieTEyMyIsImlhdCI6MTY2NjEzNTY1NCwiZXhwIjoxNjY2NzQwNDU0fQ.azX1i7gLJzFOQzUHRCIiFFMg-UogDLaMzG3DOaz8CKM

{
    "name": "Neverending Story 3", 
    "year": "1976", 
    "director": "Michael Bane",
    "genre": "Fantasy",
    "runtime": 120
}

###
PUT http://localhost:3000/api/movies/edit/634f36c134ff7e0f9e148a44 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNGUwZTNlNjBiY2I2ZTJkZTA0ZjMwMCIsImRpc3BsYXlOYW1lIjoiQm9iIEJvYmJ5IiwidXNlcm5hbWUiOiJib2JieTEyMyIsImlhdCI6MTY2NjEzNTY1NCwiZXhwIjoxNjY2NzQwNDU0fQ.azX1i7gLJzFOQzUHRCIiFFMg-UogDLaMzG3DOaz8CKM

{
    "name": "Neverending Story 2", 
    "year": "9999", 
    "director": "Michael Bane",
    "genre": "Fantasy",
    "runtime": 120
}

###
DELETE http://localhost:3000/api/movies/delete/634f36c134ff7e0f9e148a44 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNGUwZTNlNjBiY2I2ZTJkZTA0ZjMwMCIsImRpc3BsYXlOYW1lIjoiQm9iIEJvYmJ5IiwidXNlcm5hbWUiOiJib2JieTEyMyIsImlhdCI6MTY2NjEzNTY1NCwiZXhwIjoxNjY2NzQwNDU0fQ.azX1i7gLJzFOQzUHRCIiFFMg-UogDLaMzG3DOaz8CKM

