POST http://localhost:3000/api/auth/register HTTP/1.1
content-type: application/json

{
    "displayName": "Bob Bobby",
    "password": "123456",
    "username": "bobby123",
    "emailAddress": "Bobby@email.com"
}

###
POST http://localhost:3000/api/auth/login HTTP/1.1
content-type: application/json

{
    "password": "123456",
    "username": "bobby123"
}
